package com.van.sale.vansale.model;

import javax.xml.transform.sax.TemplatesHandler;

public class CustomerVisitLog {
    int KEY_ID,CUSTOMER_VISIT_DOC_STATUS=0,CUTOMER_VISIT_IDX=0;
    String CUSTOMER_VISIT_CUSTOMER,CUSTOMER_VISIT_REFERENCE,CUSTOMER_VISIT_CREATION,CUSTOMER_VISIT_COMMENTS,
            CUSTOMER_VISIT_LATITUDE,CUSTOMER_VISIT_LONGITUDE,CUSTOMER_VISIT_MODIFIED,CUSTOMER_VISIT_MODIFIED_BY,CUSTOMER_VISIT_NAMING_SERIES,
            CUSTOMER_VISIT_OWNER,CUSTOMER_VISIT_SALES_PERSON,CUSTOMER_VISIT_VISIT_DATE,CUSTOMER_VISIT_VISIT_RESULT,CUSTOMER_VISIT_SYNC_STATUS;
    Float CUSTOMER_VISIT_AMOUNT;

    public CustomerVisitLog() {
    }
    public CustomerVisitLog(int KEY_ID,int CUSTOMER_VISIT_DOC_STATUS,String CUSTOMER_VISIT_CUSTOMER,String CUSTOMER_VISIT_REFERENCE,String CUSTOMER_VISIT_CREATION,String CUSTOMER_VISIT_COMMENTS,
                            String CUSTOMER_VISIT_LATITUDE,String CUSTOMER_VISIT_LONGITUDE,String CUSTOMER_VISIT_MODIFIED,String CUSTOMER_VISIT_MODIFIED_BY,String CUSTOMER_VISIT_NAMING_SERIES,
                            String CUSTOMER_VISIT_OWNER,Float CUSTOMER_VISIT_AMOUNT, String CUSTOMER_VISIT_SALES_PERSON,String CUSTOMER_VISIT_VISIT_DATE,String CUSTOMER_VISIT_VISIT_RESULT,String CUSTOMER_VISIT_SYNC_STATUS) {
        this.KEY_ID=KEY_ID;
        this.CUSTOMER_VISIT_DOC_STATUS=CUSTOMER_VISIT_DOC_STATUS;
        this.CUSTOMER_VISIT_CUSTOMER=CUSTOMER_VISIT_CUSTOMER;
        this.CUSTOMER_VISIT_REFERENCE=CUSTOMER_VISIT_REFERENCE;
        this.CUSTOMER_VISIT_CREATION=CUSTOMER_VISIT_CREATION;
        this.CUSTOMER_VISIT_COMMENTS=CUSTOMER_VISIT_COMMENTS;
        this.CUSTOMER_VISIT_LATITUDE=CUSTOMER_VISIT_LATITUDE;
        this.CUSTOMER_VISIT_LONGITUDE=CUSTOMER_VISIT_LONGITUDE;
        this.CUSTOMER_VISIT_MODIFIED=CUSTOMER_VISIT_MODIFIED;
        this.CUSTOMER_VISIT_MODIFIED_BY=CUSTOMER_VISIT_MODIFIED_BY;
        this.CUSTOMER_VISIT_NAMING_SERIES=CUSTOMER_VISIT_NAMING_SERIES;
        this.CUSTOMER_VISIT_OWNER=CUSTOMER_VISIT_OWNER;
        this.CUSTOMER_VISIT_SALES_PERSON=CUSTOMER_VISIT_SALES_PERSON;
        this.CUSTOMER_VISIT_VISIT_DATE=CUSTOMER_VISIT_VISIT_DATE;
        this.CUSTOMER_VISIT_VISIT_RESULT=CUSTOMER_VISIT_VISIT_RESULT;
        this.CUSTOMER_VISIT_SYNC_STATUS=CUSTOMER_VISIT_SYNC_STATUS;
        this.CUSTOMER_VISIT_AMOUNT=CUSTOMER_VISIT_AMOUNT;
    }
    public int getCUSTOMER_VISIT_KEY_ID() {
        return KEY_ID;
    }

    public void setCUSTOMER_VISIT_KEY_ID(int KEY_ID) {
        this.KEY_ID = KEY_ID;
    }
    public int getCUSTOMER_VISIT_DOC_STATUS() {
        return CUSTOMER_VISIT_DOC_STATUS;
    }

    public void setCUSTOMER_VISIT_DOC_STATUS(int CUSTOMER_VISIT_DOC_STATUS) {
        this.CUSTOMER_VISIT_DOC_STATUS = CUSTOMER_VISIT_DOC_STATUS;
    }
    public int getCUTOMER_VISIT_IDX() {
        return CUTOMER_VISIT_IDX;
    }

    public void setCUTOMER_VISIT_IDX(int _CUTOMER_VISIT_IDX) {
        this.CUTOMER_VISIT_IDX = CUTOMER_VISIT_IDX;
    }
    public String getCUSTOMER_VISIT_CUSTOMER() {
        return CUSTOMER_VISIT_CUSTOMER;
    }

    public void setCUSTOMER_VISIT_CUSTOMER(String CUSTOMER_VISIT_CUSTOMER) {
        this.CUSTOMER_VISIT_CUSTOMER = CUSTOMER_VISIT_CUSTOMER;
    }

    public String getCUSTOMER_VISIT_REFERENCE() {
        return CUSTOMER_VISIT_REFERENCE;
    }

    public void setCUSTOMER_VISIT_REFERENCE(String CUSTOMER_VISIT_REFERENCE) {
        this.CUSTOMER_VISIT_REFERENCE = CUSTOMER_VISIT_REFERENCE;
    }

    public String getCUSTOMER_VISIT_CREATION() {
        return CUSTOMER_VISIT_CREATION;
    }

    public void setCUSTOMER_VISIT_CREATION(String CUSTOMER_VISIT_CREATION) {
        this.CUSTOMER_VISIT_CREATION = CUSTOMER_VISIT_CREATION;
    }

    public String getCUSTOMER_VISIT_COMMENTS() {
        return CUSTOMER_VISIT_COMMENTS;
    }

    public void setCUSTOMER_VISIT_COMMENTS(String CUSTOMER_VISIT_COMMENTS) {
        this.CUSTOMER_VISIT_COMMENTS = CUSTOMER_VISIT_COMMENTS;
    }

    public String getCUSTOMER_VISIT_LATITUDE() {
        return CUSTOMER_VISIT_LATITUDE;
    }

    public void setCUSTOMER_VISIT_LATITUDE(String CUSTOMER_VISIT_LATITUDE) {
        this.CUSTOMER_VISIT_LATITUDE = CUSTOMER_VISIT_LATITUDE;
    }

    public String getCUSTOMER_VISIT_LONGITUDE() {
        return CUSTOMER_VISIT_LONGITUDE;
    }

    public void setCUSTOMER_VISIT_LONGITUDE(String CUSTOMER_VISIT_LONGITUDE) {
        this.CUSTOMER_VISIT_LONGITUDE = CUSTOMER_VISIT_LONGITUDE;
    }

    public String getCUSTOMER_VISIT_MODIFIED() {
        return CUSTOMER_VISIT_MODIFIED;
    }

    public void setCUSTOMER_VISIT_MODIFIED(String CUSTOMER_VISIT_MODIFIED) {
        this.CUSTOMER_VISIT_MODIFIED = CUSTOMER_VISIT_MODIFIED;
    }

    public String getCUSTOMER_VISIT_MODIFIED_BY() {
        return CUSTOMER_VISIT_MODIFIED_BY;
    }

    public void setCUSTOMER_VISIT_MODIFIED_BY(String CUSTOMER_VISIT_MODIFIED_BY) {
        this.CUSTOMER_VISIT_MODIFIED_BY = CUSTOMER_VISIT_MODIFIED_BY;
    }

    public String getCUSTOMER_VISIT_NAMING_SERIES() {
        return CUSTOMER_VISIT_NAMING_SERIES;
    }

    public void setCUSTOMER_VISIT_NAMING_SERIES(String CUSTOMER_VISIT_NAMING_SERIES) {
        this.CUSTOMER_VISIT_NAMING_SERIES = CUSTOMER_VISIT_NAMING_SERIES;
    }

    public String getCUSTOMER_VISIT_OWNER() {
        return CUSTOMER_VISIT_OWNER;
    }

    public void setCUSTOMER_VISIT_OWNER(String CUSTOMER_VISIT_OWNER) {
        this.CUSTOMER_VISIT_OWNER = CUSTOMER_VISIT_OWNER;
    }

    public String getCUSTOMER_VISIT_SALES_PERSON() {
        return CUSTOMER_VISIT_SALES_PERSON;
    }

    public void setCUSTOMER_VISIT_SALES_PERSON(String CUSTOMER_VISIT_SALES_PERSON) {
        this.CUSTOMER_VISIT_SALES_PERSON = CUSTOMER_VISIT_SALES_PERSON;
    }

    public String getCUSTOMER_VISIT_VISIT_DATE() {
        return CUSTOMER_VISIT_VISIT_DATE;
    }

    public void setCUSTOMER_VISIT_VISIT_DATE(String CUSTOMER_VISIT_VISIT_DATE) {
        this.CUSTOMER_VISIT_VISIT_DATE = CUSTOMER_VISIT_VISIT_DATE;
    }

    public String getCUSTOMER_VISIT_VISIT_RESULT() {
        return CUSTOMER_VISIT_VISIT_RESULT;
    }

    public void setCUSTOMER_VISIT_VISIT_RESULT(String CUSTOMER_VISIT_VISIT_RESULT) {
        this.CUSTOMER_VISIT_VISIT_RESULT = CUSTOMER_VISIT_VISIT_RESULT;
    }

    public String getCUSTOMER_VISIT_SYNC_STATUS() {
        return CUSTOMER_VISIT_SYNC_STATUS;
    }
    public void setCUSTOMER_VISIT_SYNC_STATUS(String CUSTOMER_VISIT_SYNC_STATUS) {
        this.CUSTOMER_VISIT_SYNC_STATUS = CUSTOMER_VISIT_SYNC_STATUS;
    }

    public Float getCUSTOMER_VISIT_AMOUNT() {
        return CUSTOMER_VISIT_AMOUNT;
    }
    public void setCUSTOMER_VISIT_AMOUNT(Float CUSTOMER_VISIT_AMOUNT) {
        this.CUSTOMER_VISIT_AMOUNT = CUSTOMER_VISIT_AMOUNT;
    }

}
