package com.van.sale.vansale.model;

public class SalesOrderClass {


    private Float SALES_ORDER_CONVERSION_RATE,SALES_ORDER_PLC_CONVERSION_RATE;
    private int SALES_ORDER_DOC_STATUS,SYNC_STATUS,TOTAL_QUANDITY,ITEM_COUNT;
    private String KEY_ID,SALES_ORDER_CREATION,SALES_ORDER_OWNER,SALES_ORDER_BILLING_STATUS,SALES_ORDER_PO_NO,SALES_ORDER_CUSTOMER,
            SALES_ORDER_ORDER_TYPE,SALES_ORDER_STATUS,SALES_ORDER_COMPANY,SALES_ORDER_NAMING_SERIES,SALES_ORDER_DOC_NO,SALES_ORDER_DELIVERY_DATE,
            SALES_ORDER_CURRENCY,SALES_ORDER_PRICE_LIST,SALES_ORDER_DEVICE_ID,SALES_ORDER_CUSTOMER_CODE,SALES_ORDER_LATITUDE,SALES_ORDER_LONGITUDE;

    public SalesOrderClass() {
    }

    public SalesOrderClass(String SALES_ORDER_CUSTOMER, String SALES_ORDER_DELIVERY_DATE) {
        this.SALES_ORDER_CUSTOMER = SALES_ORDER_CUSTOMER;
        this.SALES_ORDER_DELIVERY_DATE = SALES_ORDER_DELIVERY_DATE;
    }

    public SalesOrderClass(Float SALES_ORDER_CONVERSION_RATE, Float SALES_ORDER_PLC_CONVERSION_RATE, int SALES_ORDER_DOC_STATUS, int SYNC_STATUS, String SALES_ORDER_CREATION, String SALES_ORDER_OWNER, String SALES_ORDER_BILLING_STATUS, String SALES_ORDER_PO_NO, String SALES_ORDER_CUSTOMER, String SALES_ORDER_ORDER_TYPE, String SALES_ORDER_STATUS, String SALES_ORDER_COMPANY, String SALES_ORDER_NAMING_SERIES, String SALES_ORDER_DOC_NO, String SALES_ORDER_DELIVERY_DATE, String SALES_ORDER_CURRENCY, String SALES_ORDER_PRICE_LIST, String SALES_ORDER_DEVICE_ID, String SALES_ORDER_LATITUDE, String SALES_ORDER_LONGITUDE) {
        this.SALES_ORDER_CONVERSION_RATE = SALES_ORDER_CONVERSION_RATE;
        this.SALES_ORDER_PLC_CONVERSION_RATE = SALES_ORDER_PLC_CONVERSION_RATE;
        this.SALES_ORDER_DOC_STATUS = SALES_ORDER_DOC_STATUS;
        this.SYNC_STATUS = SYNC_STATUS;
        this.SALES_ORDER_CREATION = SALES_ORDER_CREATION;
        this.SALES_ORDER_OWNER = SALES_ORDER_OWNER;
        this.SALES_ORDER_BILLING_STATUS = SALES_ORDER_BILLING_STATUS;
        this.SALES_ORDER_PO_NO = SALES_ORDER_PO_NO;
        this.SALES_ORDER_CUSTOMER = SALES_ORDER_CUSTOMER;
        this.SALES_ORDER_ORDER_TYPE = SALES_ORDER_ORDER_TYPE;
        this.SALES_ORDER_STATUS = SALES_ORDER_STATUS;
        this.SALES_ORDER_COMPANY = SALES_ORDER_COMPANY;
        this.SALES_ORDER_NAMING_SERIES = SALES_ORDER_NAMING_SERIES;
        this.SALES_ORDER_DOC_NO = SALES_ORDER_DOC_NO;
        this.SALES_ORDER_DELIVERY_DATE = SALES_ORDER_DELIVERY_DATE;
        this.SALES_ORDER_CURRENCY = SALES_ORDER_CURRENCY;
        this.SALES_ORDER_PRICE_LIST = SALES_ORDER_PRICE_LIST;
        this.SALES_ORDER_DEVICE_ID = SALES_ORDER_DEVICE_ID;
        this.SALES_ORDER_LATITUDE = SALES_ORDER_LATITUDE;
        this.SALES_ORDER_LONGITUDE = SALES_ORDER_LONGITUDE;

    }

    public int getITEM_COUNT() {
        return ITEM_COUNT;
    }

    public void setITEM_COUNT(int ITEM_COUNT) {
        this.ITEM_COUNT = ITEM_COUNT;
    }

    public String getSALES_ORDER_LATITUDE() {
        return SALES_ORDER_LATITUDE;
    }

    public void setSALES_ORDER_LATITUDE(String SALES_ORDER_LATITUDE) {
        this.SALES_ORDER_LATITUDE = SALES_ORDER_LATITUDE;
    }

    public String getSALES_ORDER_LONGITUDE() {
        return SALES_ORDER_LONGITUDE;
    }

    public void setSALES_ORDER_LONGITUDE(String SALES_ORDER_LONGITUDE) {
        this.SALES_ORDER_LONGITUDE = SALES_ORDER_LONGITUDE;
    }

    public String getSALES_ORDER_CUSTOMER_CODE() {
        return SALES_ORDER_CUSTOMER_CODE;
    }

    public void setSALES_ORDER_CUSTOMER_CODE(String SALES_ORDER_CUSTOMER_CODE) {
        this.SALES_ORDER_CUSTOMER_CODE = SALES_ORDER_CUSTOMER_CODE;
    }

    public int getTOTAL_QUANDITY() {
        return TOTAL_QUANDITY;
    }

    public void setTOTAL_QUANDITY(int TOTAL_QUANDITY) {
        this.TOTAL_QUANDITY = TOTAL_QUANDITY;
    }

    public Float getSALES_ORDER_CONVERSION_RATE() {
        return SALES_ORDER_CONVERSION_RATE;
    }

    public void setSALES_ORDER_CONVERSION_RATE(Float SALES_ORDER_CONVERSION_RATE) {
        this.SALES_ORDER_CONVERSION_RATE = SALES_ORDER_CONVERSION_RATE;
    }

    public Float getSALES_ORDER_PLC_CONVERSION_RATE() {
        return SALES_ORDER_PLC_CONVERSION_RATE;
    }

    public void setSALES_ORDER_PLC_CONVERSION_RATE(Float SALES_ORDER_PLC_CONVERSION_RATE) {
        this.SALES_ORDER_PLC_CONVERSION_RATE = SALES_ORDER_PLC_CONVERSION_RATE;
    }

    public int getSALES_ORDER_DOC_STATUS() {
        return SALES_ORDER_DOC_STATUS;
    }

    public void setSALES_ORDER_DOC_STATUS(int SALES_ORDER_DOC_STATUS) {
        this.SALES_ORDER_DOC_STATUS = SALES_ORDER_DOC_STATUS;
    }

    public int getSYNC_STATUS() {
        return SYNC_STATUS;
    }

    public void setSYNC_STATUS(int SYNC_STATUS) {
        this.SYNC_STATUS = SYNC_STATUS;
    }

    public String getKEY_ID() {
        return KEY_ID;
    }

    public void setKEY_ID(String KEY_ID) {
        this.KEY_ID = KEY_ID;
    }

    public String getSALES_ORDER_CREATION() {
        return SALES_ORDER_CREATION;
    }

    public void setSALES_ORDER_CREATION(String SALES_ORDER_CREATION) {
        this.SALES_ORDER_CREATION = SALES_ORDER_CREATION;
    }

    public String getSALES_ORDER_OWNER() {
        return SALES_ORDER_OWNER;
    }

    public void setSALES_ORDER_OWNER(String SALES_ORDER_OWNER) {
        this.SALES_ORDER_OWNER = SALES_ORDER_OWNER;
    }

    public String getSALES_ORDER_BILLING_STATUS() {
        return SALES_ORDER_BILLING_STATUS;
    }

    public void setSALES_ORDER_BILLING_STATUS(String SALES_ORDER_BILLING_STATUS) {
        this.SALES_ORDER_BILLING_STATUS = SALES_ORDER_BILLING_STATUS;
    }

    public String getSALES_ORDER_PO_NO() {
        return SALES_ORDER_PO_NO;
    }

    public void setSALES_ORDER_PO_NO(String SALES_ORDER_PO_NO) {
        this.SALES_ORDER_PO_NO = SALES_ORDER_PO_NO;
    }

    public String getSALES_ORDER_CUSTOMER() {
        return SALES_ORDER_CUSTOMER;
    }

    public void setSALES_ORDER_CUSTOMER(String SALES_ORDER_CUSTOMER) {
        this.SALES_ORDER_CUSTOMER = SALES_ORDER_CUSTOMER;
    }

    public String getSALES_ORDER_ORDER_TYPE() {
        return SALES_ORDER_ORDER_TYPE;
    }

    public void setSALES_ORDER_ORDER_TYPE(String SALES_ORDER_ORDER_TYPE) {
        this.SALES_ORDER_ORDER_TYPE = SALES_ORDER_ORDER_TYPE;
    }

    public String getSALES_ORDER_STATUS() {
        return SALES_ORDER_STATUS;
    }

    public void setSALES_ORDER_STATUS(String SALES_ORDER_STATUS) {
        this.SALES_ORDER_STATUS = SALES_ORDER_STATUS;
    }

    public String getSALES_ORDER_COMPANY() {
        return SALES_ORDER_COMPANY;
    }

    public void setSALES_ORDER_COMPANY(String SALES_ORDER_COMPANY) {
        this.SALES_ORDER_COMPANY = SALES_ORDER_COMPANY;
    }

    public String getSALES_ORDER_NAMING_SERIES() {
        return SALES_ORDER_NAMING_SERIES;
    }

    public void setSALES_ORDER_NAMING_SERIES(String SALES_ORDER_NAMING_SERIES) {
        this.SALES_ORDER_NAMING_SERIES = SALES_ORDER_NAMING_SERIES;
    }

    public String getSALES_ORDER_DOC_NO() {
        return SALES_ORDER_DOC_NO;
    }

    public void setSALES_ORDER_DOC_NO(String SALES_ORDER_DOC_NO) {
        this.SALES_ORDER_DOC_NO = SALES_ORDER_DOC_NO;
    }

    public String getSALES_ORDER_DELIVERY_DATE() {
        return SALES_ORDER_DELIVERY_DATE;
    }

    public void setSALES_ORDER_DELIVERY_DATE(String SALES_ORDER_DELIVERY_DATE) {
        this.SALES_ORDER_DELIVERY_DATE = SALES_ORDER_DELIVERY_DATE;
    }

    public String getSALES_ORDER_CURRENCY() {
        return SALES_ORDER_CURRENCY;
    }

    public void setSALES_ORDER_CURRENCY(String SALES_ORDER_CURRENCY) {
        this.SALES_ORDER_CURRENCY = SALES_ORDER_CURRENCY;
    }

    public String getSALES_ORDER_PRICE_LIST() {
        return SALES_ORDER_PRICE_LIST;
    }

    public void setSALES_ORDER_PRICE_LIST(String SALES_ORDER_PRICE_LIST) {
        this.SALES_ORDER_PRICE_LIST = SALES_ORDER_PRICE_LIST;
    }

    public String getSALES_ORDER_DEVICE_ID() {
        return SALES_ORDER_DEVICE_ID;
    }

    public void setSALES_ORDER_DEVICE_ID(String SALES_ORDER_DEVICE_ID) {
        this.SALES_ORDER_DEVICE_ID = SALES_ORDER_DEVICE_ID;
    }
}
