package com.van.sale.vansale.model;

public class SalesInvoiceClass {


    int KEY_ID,SALES_INVOICE_DOC_STATUS,SALES_INVOICE_IS_RETURN,QTY,ITEM_COUNT,SALES_INVOICE_IS_POS,SALES_INVOICE_UPDATE_STOCK;
     String SALES_INVOICE_CREATION,SALES_INVOICE_OWNER,SALES_INVOICE_SELLING_PRICE_LIST,SALES_INVOICE_CUSTOMER,SALES_INVOICE_COMPANY,SALES_INVOICE_NAMING_SERIES,
             SALES_INVOICE_CURRENCY,SALES_INVOICE_DOC_NO,SALES_INVOICE_RETURN_AGAINST,SALES_INVOICE_POSTING_TIME,SALES_INVOICE_POSTING_DATE,SALES_INVOICE_STATUS,
             SALES_INVOICE_DEVICE_ID,SALES_INVOICE_SYNC_STATUS,SALES_INVOICE_RETURN_AGAINST_INVOICE_NO,SALES_INVOICE_LATITUDE,SALES_INVOICE_LONGITUDE;
     Float SALES_INVOICE_CONVERSION_RATE,SALES_INVOICE_PLC_CONVERSION_RATE;

    public SalesInvoiceClass() {
    }

    public SalesInvoiceClass(int SALES_INVOICE_DOC_STATUS, int SALES_INVOICE_IS_RETURN, String SALES_INVOICE_CREATION, String SALES_INVOICE_OWNER, String SALES_INVOICE_SELLING_PRICE_LIST, String SALES_INVOICE_CUSTOMER, String SALES_INVOICE_COMPANY, String SALES_INVOICE_NAMING_SERIES, String SALES_INVOICE_CURRENCY, String SALES_INVOICE_DOC_NO, String SALES_INVOICE_RETURN_AGAINST, String SALES_INVOICE_POSTING_TIME, String SALES_INVOICE_POSTING_DATE, String SALES_INVOICE_STATUS, String SALES_INVOICE_DEVICE_ID, String SALES_INVOICE_SYNC_STATUS, Float SALES_INVOICE_CONVERSION_RATE, Float SALES_INVOICE_PLC_CONVERSION_RATE,int SALES_INVOICE_IS_POS,int SALES_INVOICE_UPDATE_STOCK,String SALES_INVOICE_RETURN_AGAINST_INVOICE_NO) {
        this.SALES_INVOICE_DOC_STATUS = SALES_INVOICE_DOC_STATUS;
        this.SALES_INVOICE_IS_RETURN = SALES_INVOICE_IS_RETURN;
        this.SALES_INVOICE_CREATION = SALES_INVOICE_CREATION;
        this.SALES_INVOICE_OWNER = SALES_INVOICE_OWNER;
        this.SALES_INVOICE_SELLING_PRICE_LIST = SALES_INVOICE_SELLING_PRICE_LIST;
        this.SALES_INVOICE_CUSTOMER = SALES_INVOICE_CUSTOMER;
        this.SALES_INVOICE_COMPANY = SALES_INVOICE_COMPANY;
        this.SALES_INVOICE_NAMING_SERIES = SALES_INVOICE_NAMING_SERIES;
        this.SALES_INVOICE_CURRENCY = SALES_INVOICE_CURRENCY;
        this.SALES_INVOICE_DOC_NO = SALES_INVOICE_DOC_NO;
        this.SALES_INVOICE_RETURN_AGAINST = SALES_INVOICE_RETURN_AGAINST;
        this.SALES_INVOICE_POSTING_TIME = SALES_INVOICE_POSTING_TIME;
        this.SALES_INVOICE_POSTING_DATE = SALES_INVOICE_POSTING_DATE;
        this.SALES_INVOICE_STATUS = SALES_INVOICE_STATUS;
        this.SALES_INVOICE_DEVICE_ID = SALES_INVOICE_DEVICE_ID;
        this.SALES_INVOICE_SYNC_STATUS = SALES_INVOICE_SYNC_STATUS;
        this.SALES_INVOICE_CONVERSION_RATE = SALES_INVOICE_CONVERSION_RATE;
        this.SALES_INVOICE_PLC_CONVERSION_RATE = SALES_INVOICE_PLC_CONVERSION_RATE;
        this.SALES_INVOICE_IS_POS = SALES_INVOICE_IS_POS;
        this.SALES_INVOICE_UPDATE_STOCK = SALES_INVOICE_UPDATE_STOCK;
        this.SALES_INVOICE_RETURN_AGAINST_INVOICE_NO=SALES_INVOICE_RETURN_AGAINST_INVOICE_NO;
    }

    public int getSALES_INVOICE_IS_POS() {
        return SALES_INVOICE_IS_POS;
    }

    public void setSALES_INVOICE_IS_POS(int SALES_INVOICE_IS_POS) {
        this.SALES_INVOICE_IS_POS = SALES_INVOICE_IS_POS;
    }

    public int getSALES_INVOICE_UPDATE_STOCK() {
        return SALES_INVOICE_UPDATE_STOCK;
    }

    public void setSALES_INVOICE_UPDATE_STOCK(int SALES_INVOICE_UPDATE_STOCK) {
        this.SALES_INVOICE_UPDATE_STOCK = SALES_INVOICE_UPDATE_STOCK;
    }

    public int getITEM_COUNT() {
        return ITEM_COUNT;
    }

    public void setITEM_COUNT(int ITEM_COUNT) {
        this.ITEM_COUNT = ITEM_COUNT;
    }

    public int getQTY() {
        return QTY;
    }

    public void setQTY(int QTY) {
        this.QTY = QTY;
    }

    public int getKEY_ID() {
        return KEY_ID;
    }

    public void setKEY_ID(int KEY_ID) {
        this.KEY_ID = KEY_ID;
    }

    public int getSALES_INVOICE_DOC_STATUS() {
        return SALES_INVOICE_DOC_STATUS;
    }

    public void setSALES_INVOICE_DOC_STATUS(int SALES_INVOICE_DOC_STATUS) {
        this.SALES_INVOICE_DOC_STATUS = SALES_INVOICE_DOC_STATUS;
    }

    public int getSALES_INVOICE_IS_RETURN() {
        return SALES_INVOICE_IS_RETURN;
    }

    public void setSALES_INVOICE_IS_RETURN(int SALES_INVOICE_IS_RETURN) {
        this.SALES_INVOICE_IS_RETURN = SALES_INVOICE_IS_RETURN;
    }

    public String getSALES_INVOICE_CREATION() {
        return SALES_INVOICE_CREATION;
    }

    public void setSALES_INVOICE_CREATION(String SALES_INVOICE_CREATION) {
        this.SALES_INVOICE_CREATION = SALES_INVOICE_CREATION;
    }

    public String getSALES_INVOICE_OWNER() {
        return SALES_INVOICE_OWNER;
    }

    public void setSALES_INVOICE_OWNER(String SALES_INVOICE_OWNER) {
        this.SALES_INVOICE_OWNER = SALES_INVOICE_OWNER;
    }

    public String getSALES_INVOICE_SELLING_PRICE_LIST() {
        return SALES_INVOICE_SELLING_PRICE_LIST;
    }

    public void setSALES_INVOICE_SELLING_PRICE_LIST(String SALES_INVOICE_SELLING_PRICE_LIST) {
        this.SALES_INVOICE_SELLING_PRICE_LIST = SALES_INVOICE_SELLING_PRICE_LIST;
    }

    public String getSALES_INVOICE_CUSTOMER() {
        return SALES_INVOICE_CUSTOMER;
    }

    public void setSALES_INVOICE_CUSTOMER(String SALES_INVOICE_CUSTOMER) {
        this.SALES_INVOICE_CUSTOMER = SALES_INVOICE_CUSTOMER;
    }

    public String getSALES_INVOICE_COMPANY() {
        return SALES_INVOICE_COMPANY;
    }

    public void setSALES_INVOICE_COMPANY(String SALES_INVOICE_COMPANY) {
        this.SALES_INVOICE_COMPANY = SALES_INVOICE_COMPANY;
    }

    public String getSALES_INVOICE_NAMING_SERIES() {
        return SALES_INVOICE_NAMING_SERIES;
    }

    public void setSALES_INVOICE_NAMING_SERIES(String SALES_INVOICE_NAMING_SERIES) {
        this.SALES_INVOICE_NAMING_SERIES = SALES_INVOICE_NAMING_SERIES;
    }

    public String getSALES_INVOICE_CURRENCY() {
        return SALES_INVOICE_CURRENCY;
    }

    public void setSALES_INVOICE_CURRENCY(String SALES_INVOICE_CURRENCY) {
        this.SALES_INVOICE_CURRENCY = SALES_INVOICE_CURRENCY;
    }

    public String getSALES_INVOICE_DOC_NO() {
        return SALES_INVOICE_DOC_NO;
    }

    public void setSALES_INVOICE_DOC_NO(String SALES_INVOICE_DOC_NO) {
        this.SALES_INVOICE_DOC_NO = SALES_INVOICE_DOC_NO;
    }

    public String getSALES_INVOICE_RETURN_AGAINST() {
        return SALES_INVOICE_RETURN_AGAINST;
    }

    public void setSALES_INVOICE_RETURN_AGAINST(String SALES_INVOICE_RETURN_AGAINST) {
        this.SALES_INVOICE_RETURN_AGAINST = SALES_INVOICE_RETURN_AGAINST;
    }

    public String getSALES_INVOICE_RETURN_AGAINST_INVOICE_NO() {
        return SALES_INVOICE_RETURN_AGAINST_INVOICE_NO;
    }
    public void setSALES_INVOICE_RETURN_AGAINST_INVOICE_NO(String SALES_INVOICE_RETURN_AGAINST_INVOICE_NO) {
        this.SALES_INVOICE_RETURN_AGAINST_INVOICE_NO = SALES_INVOICE_RETURN_AGAINST_INVOICE_NO;
    }

    public String getSALES_INVOICE_LATITUDE() {
        return SALES_INVOICE_LATITUDE;
    }
    public void setSALES_INVOICE_LATITUDE(String SALES_INVOICE_LATITUDE) {
        this.SALES_INVOICE_LATITUDE = SALES_INVOICE_LATITUDE;
    }
    public String getSALES_INVOICE_LONGITUDE() {
        return SALES_INVOICE_LONGITUDE;
    }
    public void setSALES_INVOICE_LONGITUDE(String SALES_INVOICE_LONGITUDE) {
        this.SALES_INVOICE_LONGITUDE = SALES_INVOICE_LONGITUDE;
    }

    public String getSALES_INVOICE_POSTING_TIME() {
        return SALES_INVOICE_POSTING_TIME;
    }

    public void setSALES_INVOICE_POSTING_TIME(String SALES_INVOICE_POSTING_TIME) {
        this.SALES_INVOICE_POSTING_TIME = SALES_INVOICE_POSTING_TIME;
    }

    public String getSALES_INVOICE_POSTING_DATE() {
        return SALES_INVOICE_POSTING_DATE;
    }

    public void setSALES_INVOICE_POSTING_DATE(String SALES_INVOICE_POSTING_DATE) {
        this.SALES_INVOICE_POSTING_DATE = SALES_INVOICE_POSTING_DATE;
    }

    public String getSALES_INVOICE_STATUS() {
        return SALES_INVOICE_STATUS;
    }

    public void setSALES_INVOICE_STATUS(String SALES_INVOICE_STATUS) {
        this.SALES_INVOICE_STATUS = SALES_INVOICE_STATUS;
    }

    public String getSALES_INVOICE_DEVICE_ID() {
        return SALES_INVOICE_DEVICE_ID;
    }

    public void setSALES_INVOICE_DEVICE_ID(String SALES_INVOICE_DEVICE_ID) {
        this.SALES_INVOICE_DEVICE_ID = SALES_INVOICE_DEVICE_ID;
    }

    public String getSALES_INVOICE_SYNC_STATUS() {
        return SALES_INVOICE_SYNC_STATUS;
    }

    public void setSALES_INVOICE_SYNC_STATUS(String SALES_INVOICE_SYNC_STATUS) {
        this.SALES_INVOICE_SYNC_STATUS = SALES_INVOICE_SYNC_STATUS;
    }

    public Float getSALES_INVOICE_CONVERSION_RATE() {
        return SALES_INVOICE_CONVERSION_RATE;
    }

    public void setSALES_INVOICE_CONVERSION_RATE(Float SALES_INVOICE_CONVERSION_RATE) {
        this.SALES_INVOICE_CONVERSION_RATE = SALES_INVOICE_CONVERSION_RATE;
    }

    public Float getSALES_INVOICE_PLC_CONVERSION_RATE() {
        return SALES_INVOICE_PLC_CONVERSION_RATE;
    }

    public void setSALES_INVOICE_PLC_CONVERSION_RATE(Float SALES_INVOICE_PLC_CONVERSION_RATE) {
        this.SALES_INVOICE_PLC_CONVERSION_RATE = SALES_INVOICE_PLC_CONVERSION_RATE;
    }
}
